apiVersion: v1
kind: Service
metadata:
  name: fiap-app
  namespace: default
  labels:
    app: fiap-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fiap-app 